**1.Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно**

In [1]:
import numpy as np

In [2]:
#a = np.array([i for i in range(12,25)])
a = np.arange(12,24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


**2.Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.**

In [6]:
s = [2,3,4,6,12]
for i in s:
    arr = np.reshape(a, (12//i, i)).copy()
    print(arr)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]


**3.Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).**

In [7]:
s = [[-1,2],[-1,3],[-1,4],[2,-1],[6,-1]]
for i in s:
    arr = np.reshape(a, (i[0], i[1])).copy()
    print(arr)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


**4.Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?**

In [13]:
arr = np.reshape(a, (12,1))
print(arr.ndim)
print(arr.T.ndim)

2
2


Нет, нельзя

**5.Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.**

In [31]:
a = np.random.randn(3,4)
print(a, a.size)

a2 = a.flatten()
print(a2, a2.size)

[[ 0.2088636  -1.95967012 -1.32818605  0.19686124]
 [ 0.73846658  0.17136828 -0.11564828 -0.3011037 ]
 [-1.47852199 -0.71984421 -0.46063877  1.05712223]] 12
[ 0.2088636  -1.95967012 -1.32818605  0.19686124  0.73846658  0.17136828
 -0.11564828 -0.3011037  -1.47852199 -0.71984421 -0.46063877  1.05712223] 12


**6.Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.**

In [16]:
a = np.arange(20,0,-2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


**7.Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?**

In [21]:
b = np.reshape(a, (1,-1))
#разница в размерности
print(b.ndim, a.ndim)

2 1
[[20 18 16 14 12 10  8  6  4  2]]


**8.Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.**

In [73]:
#задание совсем не понял
a = np.array([[0,0],[0,0]])
b = np.array([[1,1],[1,1],[1,1]])
v = np.concatenate((a,b), axis=0)
print(v, v.size)

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]] 10


**9.Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.** *(Не включительно?)* **Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?**

In [56]:
a = np.arange(0,12)
A = a.reshape((4,3))
At = A.T
B = A.dot(At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [57]:
#Вычислить обратную матрицу от B не получится, потому что её детерминант равен 0.
print(B.size, np.linalg.det(B))

16 0.0


**10.Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.**

In [27]:
np.random.seed(42)

**11.Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.**

In [45]:
c = np.random.randint(0,16,16)
print(c)

[ 0  2  4 14 13  2  0  4  9  6 14 13  6 10  8 14]


**12.Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.**

In [46]:
C = c.reshape(4,4)
print(C)

[[ 0  2  4 14]
 [13  2  0  4]
 [ 9  6 14 13]
 [ 6 10  8 14]]


In [60]:
D = B + C*10
print(D)

[[  5  34  63 172]
 [144  70  86 162]
 [113 146 289 342]
 [ 92 222 292 442]]


In [88]:
D_inv = np.linalg.inv(D)
print(D_inv)
print(np.linalg.det(D_inv), np.linalg.matrix_rank(D_inv))
print(type(D_inv))

[[-0.00221199  0.00809956  0.00092421 -0.00282295]
 [-0.01376725  0.00030688 -0.01095042  0.01371787]
 [-0.00415996 -0.00524504  0.01076887 -0.00479128]
 [ 0.01012339  0.00162503 -0.00180666 -0.00087466]]
3.9761020363209016e-09 4
<class 'numpy.ndarray'>


**13.Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.**

In [89]:
print(type(D_inv))
D_inv = D_inv.flatten()
D_inv = [0 if d_ < 0 else 1 for d_ in D_inv]
D_inv = np.array(D_inv).reshape(4,4)

<class 'numpy.ndarray'>
[[0 1 1 0]
 [0 1 0 1]
 [0 0 1 0]
 [1 1 0 0]]


In [91]:
E = np.where(D_inv, B, C)
print(E)

[[  0  14  23  14]
 [ 13  50   0 122]
 [  9   6 149  13]
 [ 32 122   8  14]]
